"""added auto-votes

Revision ID: e30a1d423ba3
Revises: 491b7e9ebcb2
Create Date: 2024-02-22 02:10:10.050401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30a1d423ba3'
down_revision: Union[str, None] = '491b7e9ebcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(), 
               server_default="True",
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('votes')
    # ### end Alembic commands ###
