name: Build and Deploy code
on:
    push:
        branches: 
            - "main"
    pull_request:
        branches:
            - "main"
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            -   name: Pulling the git repo
                uses: actions/checkout@v4
            -   name: Saying hi to the user
                run: echo "Hi User!"
            -   name: Install Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.10' 
            -   name: Upgrade pip
                run: python -m pip install --upgrade
            -   name: Install all the dependencies
                run: pip install -r requirements.txt
            -   name: Testing with pytest
                run: |
                    pip install pytest
                    pytest -v

