name: Build and Deploy Code
on: 
    push: 
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

jobs:
    job1: 
        runs-on: ubuntu-lastest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v4
            - name: say hi to the user
              run: echo "Hello User"